name: CI
on: 
  push: 
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        
      - name: Build antora-ui
        run: |
          npm install -g gulp-cli
          gulp bundle
      
      - name: Save build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: antora-ui-artifact
          path: ./build/ui-bundle.zip